apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.helm_service_b56e8912f5b05d5bbbbec42cc654add4.name   }}
spec:
  type: {{ .Values.helm_service_b56e8912f5b05d5bbbbec42cc654add4.type }}
  ports:
    - port: {{ .Values.helm_service_b56e8912f5b05d5bbbbec42cc654add4.port }}
      targetPort: {{ .Values.helm_service_b56e8912f5b05d5bbbbec42cc654add4.target_port }}
      protocol: {{.Values.helm_service_b56e8912f5b05d5bbbbec42cc654add4.protocol}}
  {{- with .Values.helm_service_b56e8912f5b05d5bbbbec42cc654add4.selector_labels }}
  selector:
      {{- toYaml . | nindent 8 }}
  {{- end }}