{{- if .Values.helm_hpa_9a5e45faf1af5f8cadd2a8b4d9a49b0a.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.helm_hpa_9a5e45faf1af5f8cadd2a8b4d9a49b0a.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.helm_hpa_9a5e45faf1af5f8cadd2a8b4d9a49b0a.workload_kind }}
    name: {{ .Values.helm_hpa_9a5e45faf1af5f8cadd2a8b4d9a49b0a.workload_name }}
  minReplicas: {{ .Values.helm_hpa_9a5e45faf1af5f8cadd2a8b4d9a49b0a.min_replicas }}
  maxReplicas: {{ .Values.helm_hpa_9a5e45faf1af5f8cadd2a8b4d9a49b0a.max_replicas }}
  metrics:
    {{- if .Values.helm_hpa_9a5e45faf1af5f8cadd2a8b4d9a49b0a.target_cpu_utilization_percentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_9a5e45faf1af5f8cadd2a8b4d9a49b0a.target_cpu_utilization_percentage }}
    {{- end }}
    {{- if .Values.helm_hpa_9a5e45faf1af5f8cadd2a8b4d9a49b0a.target_memory_utilization_percentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_9a5e45faf1af5f8cadd2a8b4d9a49b0a.target_memory_utilization_percentage }}
    {{- end }}
{{- end }}