apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.helm_service_account_f2e87782b8df5278aaccfa785aadd965.name  }}
  labels:
  {{- range $key, $value := .Values.helm_service_account_f2e87782b8df5278aaccfa785aadd965.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.helm_service_account_f2e87782b8df5278aaccfa785aadd965.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
automountServiceAccountToken: {{ .Values.helm_service_account_f2e87782b8df5278aaccfa785aadd965.automount }}
